"""update fuel supplier table

Revision ID: d288b466d82e
Revises: a8d586483066
Create Date: 2024-06-01 17:28:46.260948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd288b466d82e'
down_revision = 'a8d586483066'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'fuel_suppliers', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fuel_suppliers', type_='unique')
    # ### end Alembic commands ###
